### PR TITLE
Symlink LibreOffice and use reverse-DNS

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**

### CODE REVIEW

**Comment by Ashwatthaamaa** [comment]
I actually did the reverse DNS from flathub so that `startcenter` and `main` are symlinked to `org.libreoffice.LibreOffice.main`, that is correct right? also are there R-DNS names for other files?

**Comment by TheEvilSkeleton** [comment]
@Ashwatthaamaa your symlinks are problematic because they hardcode the path of the source icons: https://github.com/Ashwatthaamaa/Neuwaita/commit/46c72fbba46b1801d7fb3c60b0601820e4342b88.

These symlinks will work for you, but it won't work for us.

**Comment by Ashwatthaamaa** [comment]
@TheEvilSkeleton I see I was making the links from nautilus maybe that is why, so it is better to do using `ln` command rt? , I didn't merge that one because it was having some merge conflict. Can u make new PR? sorry for that n thanks for the tip :)

**Comment by TheEvilSkeleton** [comment]
Yes. `ln -s` is the way to go. I'll make a new PR and close this one.

**Pull request closed without merging**
